# Generated by Django 3.1.1 on 2021-03-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='score',
            field=models.PositiveIntegerField(),
        ),
    ]
