# Generated by Django 3.1.1 on 2021-03-04 13:15

from django.db import migrations


def migrate(apps, schema_editor):
    Organization = apps.get_model('api', 'Organization')
    Organization.objects.create(login='instruct-br', name='Instruct', score=0)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210303_2137'),
    ]

    operations = [
        migrations.RunPython(migrate)
    ]
